[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { workspace = true }
pmp = { path = "../pmp" }
sbi = { path = "../sbi" }
console = { path = "../console" }
macros = { path = "../macros" }