[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { workspace = true }
pmp = { path = "../pmp" }
sbi = { path = "../sbi" }
htee_console = { path = "../htee_console" }
htee_macro = { path = "../htee_macro" }