[package]
name = "elf-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vm = { path = "../vm" }
xmas-elf = "0.8"
log = "0.4.20"
bitflags = "2.4.2"
