[package]
name = "hsm"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = { workspace = true }
riscv = { workspace = true }
sbi = { path = "../sbi" }
pmp = { path = "../pmp" }
heapless = { workspace = true }