[package]
name = "pmp"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { workspace = true }
heapless = { workspace = true }
console = { path = "../console" }
pma = { path = "../pma" }
macros = { path = "../macros" }