[package]
name = "htee_console"
version = "0.1.0"
edition = "2024"

[features]
debug = []
info = []
trace = []
error = []

[dependencies]
# htee_device = { path = "../htee_device" }
htee_device = { workspace = true }
uart = { path = "../uart" }
spin = "0.9"
