[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+relax", "-C", "target-feature=+crt-static"]
linker = "riscv64-unknown-linux-gnu-gcc"
ar = "riscv64-unknown-linux-gnu-ar"
